### ISSUE TITLE
zfs-dkms fails to compile kernel module on a Raspberry Pi 2

### ISSUE THREAD

**Issue by flongo82** [lxc/lxd#3048]
Hi,
probably this is not the right place to post this so if that's the case please point me to the right direction. 

I flashed an ubuntu-16.04.2-preinstalled-server-armhf+raspi2.img.xz image on a Raspberry Pi 2 and wanted to install the latest version of LXD with ZFS support: 

```
sudo apt update
sudo apt upgrade -y
sudo sh -c "echo '127.0.0.1 ubuntu' >> /etc/hosts"
sudo reboot
sudo add-apt-repository -y  ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get install -y lxd lxd-tools criu cgmanager zfs
```
However, while installing zfs-dkms the following error appears: 

```
Error! Bad return status for module build on kernel: 4.4.0-1046-raspi2 (armv7l)
Consult /var/lib/dkms/zfs/0.6.5.6/build/make.log for more information.
```

Here's the content of the log file (only relevant rows): 

```
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c: In function ‘__zpl_xattr_acl_set_access’:
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:1284:28: warning: passing argument 1 of ‘posix_acl_valid’ from incompatible pointer type [-Wincompatible-pointer-types]
    error = posix_acl_valid(acl);
                            ^
In file included from /var/lib/dkms/zfs/0.6.5.6/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: expected ‘struct user_namespace *’ but argument is of type ‘struct posix_acl *’
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:1284:12: error: too few arguments to function ‘posix_acl_valid’
    error = posix_acl_valid(acl);
            ^
In file included from /var/lib/dkms/zfs/0.6.5.6/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: declared here
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c: In function ‘__zpl_xattr_acl_set_default’:
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:1323:28: warning: passing argument 1 of ‘posix_acl_valid’ from incompatible pointer type [-Wincompatible-pointer-types]
    error = posix_acl_valid(acl);
                            ^
In file included from /var/lib/dkms/zfs/0.6.5.6/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: expected ‘struct user_namespace *’ but argument is of type ‘struct posix_acl *’
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:1323:12: error: too few arguments to function ‘posix_acl_valid’
    error = posix_acl_valid(acl);
            ^
In file included from /var/lib/dkms/zfs/0.6.5.6/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.6/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: declared here
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.6.5.6/build/module/zfs/zpl_xattr.o] Error 1
scripts/Makefile.build:403: recipe for target '/var/lib/dkms/zfs/0.6.5.6/build/module/zfs' failed
make[4]: *** [/var/lib/dkms/zfs/0.6.5.6/build/module/zfs] Error 2
Makefile:1420: recipe for target '_module_/var/lib/dkms/zfs/0.6.5.6/build/module' failed
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.5.6/build/module] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-4.4.0-1046-raspi2'
Makefile:16: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.5.6/build/module'
Makefile:685: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.6.5.6/build'
Makefile:556: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea? 

Thanks.

**Comment by stgraber** [comment]
That's got nothing to do with LXD, it's a build failure of the zfs kernel module on your board's kernel.

Also note that your board is running a 32bit kernel and system. ZFS only supports 64bit systems so even if you managed to somehow compile it, you'd run into guaranteed data corruption.

**Comment by flongo82** [comment]
Ok thanks. I'm sorry and as I said I was aware that probably this was not the right place. 

Just not to do the same mistake again, can I ask if there is a better place than this to ask questions from a user prospective about best practices, advice and so on regarding using LXD?

**Comment by stgraber** [comment]
The lxc-users mailing list (https://lists.linuxcontainers.org) or #lxcontainers IRC channel on freenode would be good places.

In this case though, the answer is pretty simple, don't do ZFS on armhf as ZFS on any 32bit architecture is unsupported, unlikely to build and if it does, will eat your data. btrfs may be a better alternative for you here.

**Comment by flongo82** [comment]
Yes I got that but I have A LOT of other questions! ;-) 

By the way, thanks for your work on LXD! Here at the University of Messina, we are using it for research about Internet of Things, Fog/Edge computing and it is really amazing!
